version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
 
  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
 
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    expose:
      - 9113
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
#     - certbot-etc:/etc/letsencrypt
    networks:
      - app-network
 
# Certificates disabled
# certbot: # disabled as 1) *.example.com is prohibited and 2) certificates setup needed on real sites.
#   depends_on:
#     - webserver
#   image: certbot/certbot
#   container_name: certbot
#   volumes:
#     - certbot-etc:/etc/letsencrypt
#     - wordpress:/var/www/html
#   command: certonly --webroot --webroot-path=/var/www/html --email blog@example.com --agree-tos --no-eff-email --staging -d example.com -d blog.example.com

# ============ Monitoring =================:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus
    volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - app-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring-grafana
    depends_on:
      - prometheus
    volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    networks:
      - app-network

volumes:
# certbot-etc:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge

